index:
   path: /
   controller: App\Controller\IndexController::home

articles:
   path: /article/ajouter
   controller: App\Controller\IndexController::new

articleshow:
   path: /article/{id}
   controller: App\Controller\IndexController::show

updatearticle:
   path: /article/update/{id}
   controller: App\Controller\IndexController::update

deletearticle:
   path: /article/delete/{id}
   controller: App\Controller\IndexController::delete
