index:
   path: /
   controller: App\Controller\IndexController::home

new_article:
   path: /article/ajouter
   controller: App\Controller\IndexController::new

articleshow:
   path: /article/{id}
   controller: App\Controller\IndexController::show

article_update:
   path: /article/update/{id}
   controller: App\Controller\IndexController::update

deletearticle:
   path: /article/delete/{id}
   controller: App\Controller\IndexController::delete
